# Generated by Django 6.0.2 on 2026-02-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('contact_email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('logo_url', 'LOGO_URL'), ('primary_color', ' PRIMARY_COLOR'), ('company_address', 'COMPANY_ADDRESS '), ('max_delivery_attempts', 'MAX_DELIVERY_ATTEMPTS '), ('allow_cancel_after_pickup', 'ALLOW_CANCELLATION_AFTER_PICKUP '), ('default_currency', 'DEFAULT_CURRENCY '), ('min_payout_threshold', 'MIN_PAYOUT_THRESHOLD')], max_length=100)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
