# Generated by Django 6.0.2 on 2026-02-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
    ]
