<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-03-06 06:55
=======
# Generated by Django 6.0.3 on 2026-03-05 11:58
>>>>>>> 86b6841f5e67121c92cd14b50152df18a57f823c

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('refernce_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='drivers.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DriverEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='drivers.driverprofile')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='shipments.shipment')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='earnings.payout')),
            ],
        ),
    ]
