# Generated by Django 6.0.2 on 2026-02-24 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('earnings', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverearning',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='payout',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driverprofile'),
        ),
    ]
