# Generated by Django 6.0.3 on 2026-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('event', models.CharField(choices=[('shipment_status_changed', 'Shipment Status Changed'), ('payment_updated', 'Payment Updated'), ('payout_processed', 'Payout Processed')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
